import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext.jsx'
import { api } from '../api/index.js'
import { computeCallScore, scoreColor, scoreLabel } from '../utils/scoring.js'
import Topbar  from '../components/Topbar.jsx'
import Sidebar from '../components/Sidebar.jsx'

const PERSONA_COLORS = {
  'Head of IT': 'var(--purple)', 'IT Manager': 'var(--acc)',
  'Service Desk': 'var(--blue)', 'SysAdmin': 'var(--amber)',
  'CISO': 'var(--coral)', 'Technician': 'var(--green)'
}

// ── Formatters ────────────────────────────────────────────────────────────────

function fmtDate (d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-GB', {
    weekday: 'short', day: 'numeric', month: 'short', year: 'numeric'
  })
}

function fmtTime (d) {
  if (!d) return ''
  return new Date(d).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
}

function fmtDuration (sec) {
  if (!sec) return '—'
  const m = Math.floor(sec / 60), s = sec % 60
  return `${m} min${m !== 1 ? 's' : ''} ${s} sec`
}

function timeAgo (d) {
  if (!d) return '—'
  const diff = Date.now() - new Date(d)
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return 'Just now'
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  const days = Math.floor(hrs / 24)
  if (days === 1) return 'Yesterday'
  if (days < 7) return `${days} days ago`
  return fmtDate(d)
}

// ── Export generator ──────────────────────────────────────────────────────────

function generateExport (session, persona) {
  let q = null
  try { q = session.qualification_data ? JSON.parse(session.qualification_data) : null } catch {}

  const line = (label, val, width = 22) =>
    val ? `  ${(label + ':').padEnd(width)} ${val}` : null

  const sep  = '─'.repeat(54)
  const sep2 = '═'.repeat(54)

  const statusLabel = (val, yes, no) => {
    if (val === yes) return `✓ ${val}`
    if (val === no)  return `✗ ${val}`
    return val || null
  }

  // useCase may be array or old string
  const useCaseStr = Array.isArray(q?.useCase)
    ? q.useCase.join(', ')
    : (q?.useCase || null)

  // mobile — new split fields or old combined field
  const mobileStr = q
    ? (q.mobileIos && q.mobileAndroid
        ? `iOS: ${q.mobileIos}  ·  Android: ${q.mobileAndroid}`
        : q.mobileIos ? `iOS: ${q.mobileIos}`
        : q.mobileAndroid ? `Android: ${q.mobileAndroid}`
        : q.mobileEndpoints || null)
    : null

  // tool values may be arrays (new) or strings (old)
  const tv = v => Array.isArray(v) ? v.join(', ') : (v || '')
  const t = q?.tools || {}

  const qualLines = q ? [
    '',
    'QUALIFICATION',
    sep,
    line('Prospect type',  q.prospectType === 'msp' ? 'MSP' : q.prospectType === 'it' ? 'Internal IT' : null),
    line('Uses an MSP',    statusLabel(q.usesMsp, 'yes', 'no')),
    line('MSP partner',    q.mspPartner),
    line('Cloud OK',       statusLabel(q.cloudOk, 'yes', 'no')),
    line('Frankfurt OK',   statusLabel(q.cloudFrankfurt, 'yes', 'no')),
    line('Endpoints',      q.endpoints),
    line('Impl. time',     q.implTime),
    line('Name correct',   statusLabel(q.nameCorrect, 'confirmed', 'update')),
    line('Email correct',  statusLabel(q.emailCorrect, 'confirmed', 'update')),
    line('Decision maker', statusLabel(q.decisionMaker, 'dm', 'no')),
    line('Mobile devices', mobileStr),
    line('Timeline',       q.timeline),
    line('Use case',       useCaseStr),
    line('MSP / provider', q.msp),
  ].filter(Boolean) : []

  const toolEntries = [
    ['RMM / EPM',    tv(t.rmm)], ['Patching',     tv(t.patching)],
    ['3rd Party',    tv(t.thirdPartyPatching)], ['Remote Access', tv(t.remoteAccess)],
    ['Ticketing',    tv(t.ticketing)], ['MDM',          tv(t.mdm)],
    ['Backup',       tv(t.backup)], ['AV / EDR',     tv(t.avEdr)],
    ['Monitoring',   tv(t.monitoring)], ['Compliance',   tv(t.complianceTool)],
  ].filter(([, v]) => v)

  const toolLines = toolEntries.length ? [
    '',
    'TOOL STACK',
    sep,
    ...toolEntries.map(([l, v]) => line(l, v))
  ].filter(Boolean) : []

  // Notes now live in qualification_data.notes (sidebar textarea)
  const noteLines = q?.notes?.trim() ? [
    '',
    'NOTES',
    sep,
    ...q.notes.trim().split('\n').map(l => `  ${l}`)
  ] : []

  return [
    sep2,
    'NINJAONE CALL SUMMARY',
    sep2,
    '',
    line('Persona',  persona || session.name),
    line('Date',     fmtDate(session.started_at)),
    line('Time',     fmtTime(session.started_at)),
    line('Duration', fmtDuration(session.duration_sec)),
    ...qualLines,
    ...toolLines,
    ...noteLines,
    '',
    sep2,
    'Generated by NinjaOne Sales Companion',
    sep2,
  ].filter(Boolean).join('\n')
}

// ── Qualification summary (expanded view) ─────────────────────────────────────

function QualSummary ({ data }) {
  if (!data) return <div style={{ fontSize: 12, color: 'var(--txt3)' }}>No qualification data saved yet</div>
  let q
  try { q = typeof data === 'string' ? JSON.parse(data) : data }
  catch { return <div style={{ fontSize: 12, color: 'var(--txt3)' }}>Could not parse qualification data</div> }

  const sc = v => v === 'yes' || v === 'confirmed' || v === 'dm' ? 'var(--green)' : v === 'no' || v === 'update' ? 'var(--red)' : 'var(--amber)'
  const t  = q.tools || {}
  const tools = [['RMM/EPM', t.rmm], ['Patching', t.patching], ['3rd Party', t.thirdPartyPatching], ['Remote Access', t.remoteAccess], ['Ticketing', t.ticketing], ['MDM', t.mdm], ['Backup', t.backup], ['AV/EDR', t.avEdr], ['Monitoring', t.monitoring], ['Compliance', t.complianceTool]]
    .map(([l, v]) => [l, Array.isArray(v) ? v.join(', ') : v])
    .filter(([, v]) => v)

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
      <div>
        <div className="section-label" style={{ marginBottom: 8 }}>Status checks</div>
        {q.prospectType && (
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
            <span style={{ fontSize: 12, color: 'var(--txt2)' }}>Prospect type</span>
            <span style={{ fontSize: 11, fontWeight: 600, color: q.prospectType === 'msp' ? 'var(--blue)' : 'var(--acc)' }}>
              {q.prospectType === 'msp' ? 'MSP' : 'Internal IT'}
            </span>
          </div>
        )}
        {[['Uses an MSP', q.usesMsp], ['Cloud OK', q.cloudOk], ['Frankfurt OK', q.cloudFrankfurt], ['Name correct', q.nameCorrect], ['Email correct', q.emailCorrect], ['Decision maker', q.decisionMaker]].filter(([, v]) => v).map(([l, v]) => (
          <div key={l} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
            <span style={{ fontSize: 12, color: 'var(--txt2)' }}>{l}</span>
            <span style={{ fontSize: 11, fontWeight: 600, color: sc(v) }}>{v}</span>
          </div>
        ))}
        <div className="section-label" style={{ marginTop: 14, marginBottom: 8 }}>Qualification</div>
        {[['Endpoints', q.endpoints], ['Impl. time', q.implTime], ['Timeline', q.timeline], ['MSP', q.msp]].filter(([, v]) => v).map(([l, v]) => (
          <div key={l} style={{ display: 'flex', gap: 8, marginBottom: 5 }}>
            <span style={{ fontSize: 11, color: 'var(--txt3)', minWidth: 70 }}>{l}</span>
            <span style={{ fontSize: 12 }}>{v}</span>
          </div>
        ))}
        {q.useCase && (
          <div style={{ marginTop: 8 }}>
            <div style={{ fontSize: 11, color: 'var(--txt3)', marginBottom: 3 }}>Use case</div>
            {Array.isArray(q.useCase) ? (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {q.useCase.map(u => (
                  <span key={u} style={{ fontSize: 11, fontWeight: 500, color: 'var(--acc)', background: 'var(--acc2)', border: '1px solid var(--acc)40', borderRadius: 999, padding: '2px 8px' }}>{u}</span>
                ))}
              </div>
            ) : (
              <div style={{ fontSize: 12, color: 'var(--acc)', fontWeight: 500, lineHeight: 1.4 }}>{q.useCase}</div>
            )}
          </div>
        )}
        {(q.mobileIos || q.mobileAndroid || q.mobileEndpoints) && (
          <div style={{ display: 'flex', gap: 8, marginTop: 5 }}>
            <span style={{ fontSize: 11, color: 'var(--txt3)', minWidth: 70 }}>Mobile</span>
            <span style={{ fontSize: 12 }}>
              {q.mobileIos && q.mobileAndroid
                ? `iOS: ${q.mobileIos} · Android: ${q.mobileAndroid}`
                : q.mobileIos ? `iOS: ${q.mobileIos}`
                : q.mobileAndroid ? `Android: ${q.mobileAndroid}`
                : q.mobileEndpoints}
            </span>
          </div>
        )}
      </div>
      <div>
        {tools.length > 0 && <>
          <div className="section-label" style={{ marginBottom: 8 }}>Tool stack</div>
          {tools.map(([l, v]) => (
            <div key={l} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
              <span style={{ fontSize: 11, color: 'var(--txt3)' }}>{l}</span>
              <span style={{ fontSize: 12, color: 'var(--amber)', fontWeight: 500 }}>{v}</span>
            </div>
          ))}
        </>}
        {q.notes && <div style={{ marginTop: 14 }}><div className="section-label" style={{ marginBottom: 6 }}>Qual notes</div><div style={{ fontSize: 12, color: 'var(--txt2)', lineHeight: 1.5, background: 'var(--card)', padding: '8px 10px', borderRadius: 8 }}>{q.notes}</div></div>}
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ProspectList () {
  const { dispatch } = useApp()
  const navigate = useNavigate()
  const [prospects,    setProspects]    = useState([])
  const [loading,      setLoading]      = useState(true)
  const [expandedId,   setExpandedId]   = useState(null)
  const [expandedData, setExpandedData] = useState(null)
  const [loadingExp,   setLoadingExp]   = useState(false)
  const [copied,       setCopied]       = useState(false)

  useEffect(() => { load() }, [])

  async function load () {
    setLoading(true)
    try { setProspects(await api.prospects.list()) }
    finally { setLoading(false) }
  }

  async function continueCall (prospect) {
    // Get the most recent session for this prospect and restore its data
    const full = await api.prospects.get(prospect.id)
    const latestSession = full.sessions?.[0]

    if (!latestSession) {
      // No session yet — create one
      dispatch({ type: 'SET_PROSPECT', payload: prospect })
      dispatch({ type: 'SET_PERSONA',  payload: prospect.name })
      const session = await api.sessions.start(prospect.id)
      dispatch({ type: 'SET_SESSION',  payload: session })
      navigate('/dashboard')
      return
    }

    // Get full session with qual data
    const sessionDetail = await api.sessions.get(latestSession.id)

    // Restore qualification data to localStorage so the form pre-populates
    if (sessionDetail.qualification_data) {
      try {
        const qualData = typeof sessionDetail.qualification_data === 'string'
          ? JSON.parse(sessionDetail.qualification_data)
          : sessionDetail.qualification_data
        localStorage.setItem(`qual_${latestSession.id}`, JSON.stringify(qualData))
      } catch {}
    }

    dispatch({ type: 'SET_PROSPECT', payload: prospect })
    dispatch({ type: 'SET_PERSONA',  payload: prospect.name })
    dispatch({ type: 'SET_SESSION',  payload: latestSession })
    navigate('/dashboard')
  }

  async function toggleExpand (id) {
    if (expandedId === id) { setExpandedId(null); setExpandedData(null); return }
    setExpandedId(id)
    setExpandedData(null)
    setLoadingExp(true)
    try {
      // Get all sessions for this prospect and use the most recent one
      const full = await api.prospects.get(id)
      const latestSession = full.sessions?.[0]
      if (latestSession) {
        const sessionDetail = await api.sessions.get(latestSession.id)
        setExpandedData({ ...full, sessionDetail })
      } else {
        setExpandedData(full)
      }
    } finally { setLoadingExp(false) }
  }

  async function deleteProspect (id) {
    if (!window.confirm('Delete this session and all its data? This cannot be undone.')) return
    await api.prospects.remove(id)
    setProspects(prev => prev.filter(p => p.id !== id))
    if (expandedId === id) { setExpandedId(null); setExpandedData(null) }
  }

  function handleExport (p) {
    if (!expandedData) return
    const sd = expandedData.sessionDetail
    if (!sd) return
    const text = generateExport(sd, p.name)
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const c = name => PERSONA_COLORS[name] || 'var(--acc)'

  return (
    <div className="app-shell">
      <Topbar />
      <div className="body-shell">
        <Sidebar />
        <div className="main-scroll" style={{ padding: '24px 28px' }}>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
            <div>
              <div style={{ fontSize: 20, fontWeight: 600, letterSpacing: '-0.3px', marginBottom: 3 }}>Sessions</div>
              <div style={{ fontSize: 13, color: 'var(--txt2)' }}>{prospects.length} session{prospects.length !== 1 ? 's' : ''} recorded</div>
            </div>
            <button onClick={() => navigate('/')} className="btn btn-primary">+ New session</button>
          </div>

          {loading && <div style={{ textAlign: 'center', padding: 40, color: 'var(--txt3)', fontSize: 13 }}>Loading…</div>}
          {!loading && prospects.length === 0 && <div style={{ textAlign: 'center', padding: 60, color: 'var(--txt3)', fontSize: 13 }}>No sessions yet. Start a call from the home screen.</div>}

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {prospects.map(p => {
              const isExpanded = expandedId === p.id
              const color = c(p.name)

              return (
                <div key={p.id} style={{
                  background: 'var(--card)',
                  border: `1px solid ${isExpanded ? color + '50' : 'var(--brd)'}`,
                  borderRadius: 12, overflow: 'hidden', transition: 'border-color 0.15s'
                }}>

                  {/* Row */}
                  <div
                    onClick={() => toggleExpand(p.id)}
                    style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '14px 18px', cursor: 'pointer', background: isExpanded ? 'var(--card2)' : 'transparent' }}
                  >
                    {/* Avatar */}
                    <div style={{ width: 40, height: 40, borderRadius: 10, background: color + '20', color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, fontWeight: 700, flexShrink: 0 }}>
                      {p.name?.slice(0, 1)}
                    </div>

                    {/* Info */}
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
                        <span style={{ fontSize: 14, fontWeight: 600 }}>{p.name}</span>
                        <span className="tag" style={{ background: color + '18', color }}>{p.company || p.role || 'Persona'}</span>
                      </div>
                      {/* Date + time ago */}
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        {p.last_session_at && (
                          <span style={{ fontSize: 12, fontWeight: 500, color: 'var(--txt2)' }}>
                            {fmtDate(p.last_session_at)}
                          </span>
                        )}
                        <span style={{ fontSize: 11, color: 'var(--txt3)' }}>
                          {timeAgo(p.last_session_at)}
                        </span>
                      </div>
                    </div>

                    {/* Stats */}
                    <div style={{ display: 'flex', gap: 16, alignItems: 'center', flexShrink: 0 }}>
                      <div style={{ textAlign: 'center' }}>
                        <div style={{ fontSize: 14, fontWeight: 600 }}>{p.session_count || 0}</div>
                        <div style={{ fontSize: 10, color: 'var(--txt3)' }}>sessions</div>
                      </div>
                    </div>

                    {/* Actions */}
                    <div style={{ display: 'flex', gap: 6, flexShrink: 0 }} onClick={e => e.stopPropagation()}>
                      <button onClick={() => continueCall(p)} style={{ padding: '6px 12px', borderRadius: 8, fontSize: 12, fontWeight: 600, background: 'var(--acc)', color: '#042D22' }}>
                        Continue call
                      </button>
                      <button
                        onClick={() => toggleExpand(p.id)}
                        style={{ padding: '6px 10px', borderRadius: 8, fontSize: 12, background: isExpanded ? color + '18' : 'var(--brd2)', color: isExpanded ? color : 'var(--txt2)', border: '1px solid var(--brd)' }}
                      >
                        {isExpanded ? '▲' : '▼'}
                      </button>
                    </div>
                  </div>

                  {/* Expanded detail */}
                  {isExpanded && (
                    <div style={{ padding: '16px 18px 20px', borderTop: `1px solid ${color + '30'}`, background: 'var(--card2)', animation: 'fadeUp 0.18s ease' }}>

                      {loadingExp && <div style={{ fontSize: 12, color: 'var(--txt3)' }}>Loading…</div>}

                      {expandedData && (() => {
                        const sd = expandedData.sessionDetail
                        return (
                          <>
                            {/* Session date header */}
                            {sd && (() => {
                              let qual = null
                              try { qual = sd.qualification_data ? JSON.parse(sd.qualification_data) : null } catch {}
                              const score = computeCallScore(qual, qual?.notes || '')
                              return (
                                <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16, padding: '8px 14px', background: 'var(--card)', borderRadius: 9, border: '1px solid var(--brd)' }}>
                                  <div>
                                    <span style={{ fontSize: 12, fontWeight: 600 }}>{fmtDate(sd.started_at)}</span>
                                    <span style={{ fontSize: 12, color: 'var(--txt2)', marginLeft: 10 }}>{fmtTime(sd.started_at)}</span>
                                  </div>
                                  {sd.duration_sec && (
                                    <span style={{ fontSize: 11, color: 'var(--txt3)', marginLeft: 8 }}>
                                      Duration: {fmtDuration(sd.duration_sec)}
                                    </span>
                                  )}
                                  <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 7, background: scoreColor(score) + '15', border: `1px solid ${scoreColor(score)}40`, borderRadius: 999, padding: '4px 12px' }}>
                                    <span style={{ fontSize: 11, color: 'var(--txt2)' }}>Call quality</span>
                                    <span style={{ fontSize: 15, fontWeight: 800, color: scoreColor(score), fontVariantNumeric: 'tabular-nums' }}>{score}</span>
                                    <span style={{ fontSize: 10, fontWeight: 600, color: scoreColor(score) }}>{scoreLabel(score)}</span>
                                  </div>
                                </div>
                              )
                            })()}

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', gap: 24 }}>

                              {/* Qualification */}
                              <div>
                                <div className="section-label" style={{ marginBottom: 12 }}>Qualification summary</div>
                                <QualSummary data={sd?.qualification_data} />
                              </div>

                              {/* Qual notes — moved from sidebar */}
                              <div>
                                <div className="section-label" style={{ marginBottom: 12 }}>Notes</div>
                                {(() => {
                                  let qualNotes = ''
                                  try {
                                    const q = sd?.qualification_data ? JSON.parse(sd.qualification_data) : null
                                    qualNotes = q?.notes || ''
                                  } catch {}
                                  return qualNotes ? (
                                    <div style={{ background: 'var(--card)', border: '1px solid var(--brd)', borderRadius: 9, padding: '10px 12px', fontSize: 12, lineHeight: 1.6, color: 'var(--txt)', whiteSpace: 'pre-wrap' }}>
                                      {qualNotes}
                                    </div>
                                  ) : (
                                    <div style={{ fontSize: 12, color: 'var(--txt3)' }}>No notes for this session</div>
                                  )
                                })()}
                              </div>
                            </div>

                            {/* Footer actions */}
                            <div style={{ display: 'flex', gap: 8, marginTop: 16, paddingTop: 14, borderTop: '1px solid var(--brd)', alignItems: 'center' }}>
                              <button onClick={() => continueCall(p)} className="btn btn-primary" style={{ fontSize: 12, padding: '7px 16px' }}>
                                Continue call
                              </button>
                              <button
                                onClick={() => handleExport(p)}
                                style={{
                                  padding: '7px 16px', borderRadius: 8, fontSize: 12, fontWeight: 500,
                                  background: copied ? 'var(--green2)' : 'var(--acc2)',
                                  color: copied ? 'var(--green)' : 'var(--acc)',
                                  border: `1px solid ${copied ? 'var(--green)' : 'var(--acc)'}40`
                                }}
                              >
                                {copied ? '✓ Copied!' : 'Copy summary'}
                              </button>
                              <div style={{ flex: 1 }} />
                              <button onClick={() => deleteProspect(p.id)} className="btn btn-danger" style={{ fontSize: 12, padding: '7px 16px' }}>
                                Delete
                              </button>
                            </div>
                          </>
                        )
                      })()}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </div>
    </div>
  )
}
